"use client";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { siteConfig } from "@/config/site";

const ImprintPage: React.FC = () => {
  return (
    <div className="min-h-screen w-screen py-20 flex flex-col items-center gap-8 px-4 md:px-8 bg-gray-50 text-slate-700">
      {/* Imprint Card Section */}
      <div className="w-full max-w-5xl flex flex-col items-center justify-start gap-8 px-4 md:px-8 mt-10">
        <Card className="w-full md:w-3/4 lg:w-3/4 shadow-lg bg-white rounded-lg border border-gray-200 p-6">
          <CardHeader>
            <CardTitle className="text-3xl md:text-4xl font-bold text-center md:text-left">
              Imprint
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-sm md:text-base text-left mt-4">
              <h2 className="text-xl md:text-2xl font-semibold mb-2">
                Information According to § 5 TMG
              </h2>
              <p className="mb-4">
                {siteConfig.authorName} <br />
                {siteConfig.companyName} <br />
                {siteConfig.streetAddress} <br />
                {siteConfig.city}, {siteConfig.zipCode} <br />
                {siteConfig.country}
              </p>

              <h2 className="text-xl md:text-2xl font-semibold mb-2">
                Contact
              </h2>
              <p className="mb-4">
                Phone: {siteConfig.contactPhone} <br />
                Email:{" "}
                <a
                  href={`mailto:${siteConfig.contactEmail}`}
                  className="text-blue-500 underline hover:text-blue-700"
                >
                  {siteConfig.contactEmail}
                </a>
              </p>

              <h2 className="text-xl md:text-2xl font-semibold mb-2">VAT ID</h2>
              <p className="mb-4">
                VAT identification number according to § 27 a of the German VAT
                Act: {siteConfig.vatId}
              </p>

              <h2 className="text-xl md:text-2xl font-semibold mb-2">
                Disclaimer
              </h2>
              <p className="mb-4">
                <strong>Accountability for content:</strong> The contents of our
                pages have been created with the utmost care. However, we cannot
                guarantee the contents&apos; accuracy, completeness, or
                topicality. According to statutory provisions, we are
                furthermore responsible for our own content on these web pages.
                In this context, please note that we are not obliged to monitor
                the transmitted or saved information of third parties, or
                investigate circumstances pointing to illegal activity.
              </p>
              <p className="mb-4">
                <strong>Accountability for links:</strong> Responsibility for
                the content of external links (to web pages of third parties)
                lies solely with the operators of the linked pages. No
                violations were evident to us at the time of linking. Should any
                legal infringement become known to us, we will remove the
                respective link immediately.
              </p>

              <h2 className="text-xl md:text-2xl font-semibold mb-2">
                Privacy Policy
              </h2>
              <p className="mb-4">
                This website uses Google Analytics, a web analytics service
                provided by Google LLC. Google Analytics uses "cookies", which
                are text files placed on your computer, to help the website
                analyze how users interact with the site. The information
                generated by the cookie about your use of the website will be
                transmitted to and stored by Google on servers in the United
                States. We use this information to evaluate your use of the
                website, compile reports on website activity, and provide other
                services related to website activity and internet usage. You can
                prevent Google Analytics from using your data by installing the
                opt-out browser add-on provided by Google.
              </p>
              <p className="mb-4">
                For more information on how Google handles your data, please
                refer to their{" "}
                <a
                  href="https://policies.google.com/privacy"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-500 underline hover:text-blue-700"
                >
                  privacy policy
                </a>
                .
              </p>

              <h2 className="text-xl md:text-2xl font-semibold mb-2">
                Credits
              </h2>
              <p className="mb-4">
                Built by{" "}
                <a
                  href={siteConfig.links.homepage}
                  target="_blank"
                  rel="noreferrer"
                  className="text-blue-500 underline hover:text-blue-700"
                >
                  Thomas Schwabauer
                </a>{" "}
                in 2024.
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default ImprintPage;
